# TemplateCIConfig { bench: BenchEntry { run: false, version: "nightly", install_commandline: None, commandline: "cargo bench" }, clippy: ClippyEntry { run: true, version: "stable", install_commandline: Some("rustup component add clippy"), commandline: "cargo clippy -- -D warnings" }, rustfmt: RustfmtEntry { run: true, version: "stable", install_commandline: Some("rustup component add rustfmt"), commandline: "cargo fmt -v -- --check" }, additional_matrix_entries: {"something_custom": CustomEntry { run: false, version: "stable", install_commandline: Some("echo \"installing for custom tests\""), commandline: "echo \"running custom tests\"" }}, cache: "cargo", os: "linux", dist: "xenial", versions: ["stable", "nightly"], test_commandline: "cargo test --verbose --all" }
os:
  - "linux"
dist: "xenial"

language: rust
sudo: required
cache: cargo

rust:
  - stable
  - nightly

env:
  global:
    - RUN_TEST=true
    - RUN_CLIPPY=false
    - RUN_BENCH=false
    - RUN_SOMETHING_CUSTOM=false

matrix:
  fast_finish: true
  include:
    - &rustfmt_build
      rust: "stable"
      env:
        - RUN_RUSTFMT=true
        - RUN_TEST=false
    - &clippy_build
      rust: "stable"
      env:
        - RUN_CLIPPY=true
        - RUN_TEST=false
    - &something_custom
      rust: "stable"
      env:
        - "RUN_TEST=false"
        - "RUN_SOMETHING_CUSTOM=true"

before_script:
  - bash -c 'if [[ "$RUN_RUSTFMT" == "true" ]]; then
      rustup component add rustfmt
      ;
    fi'
  - bash -c 'if [[ "$RUN_CLIPPY" == "true" ]]; then
      rustup component add clippy
      ;
    fi'
  - bash -c 'if [[ "$RUN_SOMETHING_CUSTOM" == "true" ]]; then
      echo "installing for custom tests"
      ;
    fi'

script:
  - bash -c 'if [[ "$RUN_TEST" == "true" ]]; then
      cargo test --verbose --all
      ;
    fi'
  - bash -c 'if [[ "$RUN_RUSTFMT" == "true" ]]; then
      cargo fmt -v -- --check
      ;
    fi'
  - bash -c 'if [[ "$RUN_CLIPPY" == "true" ]]; then
      cargo clippy -- -D warnings
      ;
    fi'
  - bash -c 'if [[ "$RUN_SOMETHING_CUSTOM" == "true" ]]; then
      echo "running custom tests"
      ;
    fi'

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master
    - trying
    - staging

notifications:
  email:
    on_success: never
