# TemplateCIConfig { bench: BenchEntry { run: false, version: "nightly", install_commandline: None, commandline: "cargo bench" }, clippy: ClippyEntry { run: true, version: "stable", install_commandline: Some("rustup component add clippy"), commandline: "cargo clippy -- -D warnings" }, rustfmt: RustfmtEntry { run: true, version: "stable", install_commandline: Some("rustup component add rustfmt"), commandline: "cargo fmt -v -- --check" }, additional_matrix_entries: {"something_custom": CustomEntry { run: false, version: "stable", install_commandline: Some("echo \"installing for custom tests\""), commandline: "echo \"running custom tests\"" }}, cache: "cargo", os: "linux", dist: "xenial", versions: ["stable", "nightly"], test_commandline: "cargo test --verbose --all" }
version: "2.1"

commands:
  cargo_test:
    description: "Run `cargo test`"
    steps:
      - run:
          name: "Clean out rust-toolchain"
          command: "rm -f rust-toolchain"
      - run:
          name: "Toolchain debug info"
          command: "rustc --version"
      - run:
          name: Test
          command: "cargo test"

jobs:
  test-stable:
    docker:
      - image: liuchong/rustup:stable
    steps:
      - checkout
      - cargo_test

  test-nightly:
    docker:
      - image: liuchong/rustup:nightly
    steps:
      - checkout
      - cargo_test

  test-beta:
    docker:
      - image: liuchong/rustup:beta
    steps:
      - checkout
      - cargo_test

  rustfmt:
    docker:
      - image: liuchong/rustup:stable
    steps:
      - checkout
      - run:
          name: Install
          command: rustup component add rustfmt
      - run:
          name: Rustfmt
          command: cargo fmt -v -- --check

  clippy:
    docker:
      - image: liuchong/rustup:stable
    steps:
      - checkout
      - run:
          name: Install
          command: rustup component add clippy
      - run:
          name: Clippy
          command: cargo clippy -- -D warnings

  bench:
    docker:
      - image: liuchong/rustup:nightly
    steps:
      - checkout
      - run:
          name: Bench
          command: cargo bench

workflows:
  version: 2
  continuous_integration:
    jobs:
      - test-stable:
          filters: {
  "branches": {
    "ignore": [
      "/.*\\.tmp/"
    ]
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ]
  }
}
      - test-nightly:
          filters: {
  "branches": {
    "ignore": [
      "/.*\\.tmp/"
    ]
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ]
  }
}
      - rustfmt:
          filters: {
  "branches": {
    "ignore": [
      "/.*\\.tmp/"
    ]
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ]
  }
}
      - clippy:
          filters: {
  "branches": {
    "ignore": [
      "/.*\\.tmp/"
    ]
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ]
  }
}
