# TemplateCIConfig { bench: BenchEntry { run: false, version: "nightly", install_commandline: None, commandline: "cargo bench" }, clippy: ClippyEntry { run: true, version: "stable", install_commandline: Some("rustup component add clippy"), commandline: "cargo clippy -- -D warnings" }, rustfmt: RustfmtEntry { run: true, version: "stable", install_commandline: Some("rustup component add rustfmt"), commandline: "cargo fmt -v -- --check" }, additional_matrix_entries: {"something_custom": CustomEntry { run: false, version: "stable", install_commandline: Some("echo \"installing for custom tests\""), commandline: "echo \"running custom tests\"" }}, cache: "cargo", os: "linux", dist: "xenial", versions: ["stable", "nightly"], test_commandline: "cargo test --verbose --all" }
version: 2

jobs:
  test-base:
    docker:
      - image: liuchong/rustup:stable
    steps: &test_steps
      - checkout
      - run:
          name: Debug info
          command: "rustc --version"
      - run:
          name: Test
          command: "cargo test"

  test-stable:
    docker:
      - image: liuchong/rustup:stable
    steps: *test_steps

  test-nightly:
    docker:
      - image: liuchong/rustup:nightly
    steps: *test_steps

  test-beta:
    docker:
      - image: liuchong/rustup:beta
    steps: *test_steps

  rustfmt:
    docker:
      - image: liuchong/rustup:stable
    steps:
      - checkout
      - run:
          name: Install
          command: rustup component add rustfmt
      - run:
          name: Rustfmt
          command: cargo fmt -v -- --check

  clippy:
    docker:
      - image: liuchong/rustup:stable
    steps:
      - checkout
      - run:
          name: Install
          command: rustup component add clippy
      - run:
          name: Clippy
          command: cargo clippy -- -D warnings

  bench:
    docker:
      - image: liuchong/rustup:nightly
    steps:
      - checkout
      - run:
          name: Bench
          command: cargo bench

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-stable:
          filters: {
  "branches": {
    "only": [
      "master",
      "trying",
      "staging"
    ],
    "ignore": []
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ],
    "ignore": []
  }
}
      - test-nightly:
          filters: {
  "branches": {
    "only": [
      "master",
      "trying",
      "staging"
    ],
    "ignore": []
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ],
    "ignore": []
  }
}
      - rustfmt:
          filters: {
  "branches": {
    "only": [
      "master",
      "trying",
      "staging"
    ],
    "ignore": []
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ],
    "ignore": []
  }
}
      - clippy:
          filters: {
  "branches": {
    "only": [
      "master",
      "trying",
      "staging"
    ],
    "ignore": []
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ],
    "ignore": []
  }
}
