version: 2

jobs:
  test-base:
    docker:
      - image: liuchong/rustup:stable
    steps: &test_steps
      - checkout
      - run:
          name: Debug info
          command: "rustc --version"
      - run:
          name: Test
          command: "cargo test"

  test-stable:
    docker:
      - image: liuchong/rustup:stable
    steps: *test_steps

  test-nightly:
    docker:
      - image: liuchong/rustup:nightly
    steps: *test_steps

  rustfmt:
    docker:
      - image: rust:latest
    steps:

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-stable
      - test-nightly
