version: 2

jobs:
  test-stable:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Test
          command: cargo +stable test

  test-nightly:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Test
          command: cargo +nightly test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-stable
      - test-nightly
