version: 2

jobs:
  test-base:
    docker:
      - image: liuchong/rustup:stable
    steps: &test_steps
      - checkout
      - run:
          name: Debug info
          command: "rustc --version"
      - run:
          name: Test
          command: "cargo test"

  test-stable:
    docker:
      - image: liuchong/rustup:stable
    steps: *test_steps

  test-nightly:
    docker:
      - image: liuchong/rustup:nightly
    steps: *test_steps

  test-beta:
    docker:
      - image: liuchong/rustup:beta
    steps: *test_steps

  rustfmt:
    docker:
      - image: liuchong/rustup:{{conf.rustfmt.version}}
    steps:
      - checkout
      {%- if conf.rustfmt.install_commandline.is_some() %}
      - run:
          name: Install
          command: {{conf.rustfmt.install_commandline.as_ref().unwrap().as_str()}}
      {%- endif %}
      - run:
          name: Rustfmt
          command: {{conf.rustfmt.commandline.as_str()}}

  clippy:
    docker:
      - image: liuchong/rustup:{{conf.rustfmt.version}}
    steps:
      - checkout
      {%- if conf.clippy.install_commandline.is_some() %}
      - run:
          name: Install
          command: {{conf.clippy.install_commandline.as_ref().unwrap().as_str()}}
      {%- endif %}
      - run:
          name: Clippy
          command: {{conf.clippy.commandline.as_str()}}

  bench:
    docker:
      - image: liuchong/rustup:{{conf.rustfmt.version}}
    steps:
      - checkout
      {%- if conf.bench.install_commandline.is_some() %}
      - run:
          name: Install
          command: {{conf.bench.install_commandline.as_ref().unwrap().as_str()}}
      {%- endif %}
      - run:
          name: Clippy
          command: {{conf.bench.commandline.as_str()}}

workflows:
  version: 2
  build_and_test:
    jobs:
      {%- for version in conf.versions %}
      - test-{{version}}
      {%- endfor %}
      {%- if conf.rustfmt.run %}
      - rustfmt
      {%- endif %}
      {%- if conf.clippy.run %}
      - clippy
      {%- endif %}
      {%- if conf.bench.run %}
      - bench
      {%- endif %}
