version: 2

jobs:
  test-base:
    docker:
      - image: liuchong/rustup:stable
    steps: &test_steps
      - checkout
      - run:
          name: Debug info
          command: "rustc --version"
      - run:
          name: Test
          command: "cargo test"

  test-stable:
    docker:
      - image: liuchong/rustup:stable
    steps: *test_steps

  test-nightly:
    docker:
      - image: liuchong/rustup:nightly
    steps: *test_steps

  test-beta:
    docker:
      - image: liuchong/rustup:beta
    steps: *test_steps

  rustfmt:
    docker:
      - image: liuchong/rustup:{{conf.rustfmt.version}}
    steps:
      - checkout
      - run:
          name: Install
          command: "rustup component add rustfmt"
      - run:
          name: Rustfmt
          command: "cargo fmt -v -- --check"

  clippy:
    docker:
      - image: liuchong/rustup:{{conf.rustfmt.version}}
    steps:
      - checkout
      - run:
          name: Install
          command: "rustup component add clippy"
      - run:
          name: Clippy
          command: "cargo clippy -- -D warnings"

  bench:
    docker:
      - image: liuchong/rustup:{{conf.rustfmt.version}}
    steps:
      - checkout
      - run:
          name: Install
          command: "rustup component add clippy"
      - run:
          name: Clippy
          command: "cargo bench"

workflows:
  version: 2
  build_and_test:
    jobs:
      {%- for version in conf.versions %}
      - test-{{version}}
      {%- endfor %}
      {%- if conf.rustfmt.run %}
      - rustfmt
      {%- endif %}
      {%- if conf.clippy.run %}
      - clippy
      {%- endif %}
      {%- if conf.bench.run %}
      - bench
      {%- endif %}
