version: "2.1"

commands:
  cargo_test:
    description: "Run `cargo test`"
    steps:
      - run:
          name: "Clean out rust-toolchain"
          command: "rm -f rust-toolchain"
      - run:
          name: "Toolchain debug info"
          command: "rustc --version"
      - run:
          name: Test
          command: "cargo test"

jobs:
  test-stable:
    docker:
      - image: liuchong/rustup:stable
    steps:
      - checkout
      - cargo_test

  test-nightly:
    docker:
      - image: liuchong/rustup:nightly
    steps:
      - checkout
      - cargo_test

  test-beta:
    docker:
      - image: liuchong/rustup:beta
    steps:
      - checkout
      - cargo_test

  rustfmt:
    docker:
      - image: liuchong/rustup:{{conf.rustfmt.version}}
    steps:
      - checkout
      {%- if conf.rustfmt.install_commandline.is_some() %}
      - run:
          name: Install
          command: {{conf.rustfmt.install_commandline.as_ref().unwrap().as_str()}}
      {%- endif %}
      - run:
          name: Rustfmt
          command: {{conf.rustfmt.commandline.as_str()}}

  clippy:
    docker:
      - image: liuchong/rustup:{{conf.clippy.version}}
    steps:
      - checkout
      {%- if conf.clippy.install_commandline.is_some() %}
      - run:
          name: Install
          command: {{conf.clippy.install_commandline.as_ref().unwrap().as_str()}}
      {%- endif %}
      - run:
          name: Clippy
          command: {{conf.clippy.commandline.as_str()}}

  bench:
    docker:
      - image: liuchong/rustup:{{conf.bench.version}}
    steps:
      - checkout
      {%- if conf.bench.install_commandline.is_some() %}
      - run:
          name: Install
          command: {{conf.bench.install_commandline.as_ref().unwrap().as_str()}}
      {%- endif %}
      - run:
          name: Bench
          command: {{conf.bench.commandline.as_str()}}

  ci_success:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Success
          command: "echo yay"

workflows:
  continuous_integration:
    jobs:
      {%- for version in conf.versions %}
      - test-{{version}}:
          filters: {{filters|json}}
      {%- endfor %}
      {%- if conf.rustfmt.run %}
      - rustfmt:
          filters: {{filters|json}}
      {%- endif %}
      {%- if conf.clippy.run %}
      - clippy:
          filters: {{filters|json}}
      {%- endif %}
      {%- if conf.bench.run %}
      - bench:
          filters: {{filters|json}}
      {%- endif %}
      - ci_success:
          requires:
          {%- for version in conf.versions %}
          - test-{{version}}
          {%- endfor %}
          {%- if conf.rustfmt.run %}
          - rustfmt
          {%- endif %}
          {%- if conf.clippy.run %}
          - clippy
          {%- endif %}
          {%- if conf.bench.run %}
          - bench
          {%- endif %}
